owner: DashioDevs
repo: status

assignees:
  - nicokempe

sites:
  - name: Dashio Homepage
    url: https://www.dashio.net
  - name: Dashio Status
    url: https://status.dashio.net
  - name: Dashio Docs
    url: https://docs.dashio.net
  - name: Dashio API
    url: https://api.dashio.net/rest/core/health 
  - name: Demo
    url: https://demo.dashio.net/ 

status-website:
  # Add our custom domain name, or remove the `cname` line if we don't have a domain
  cname: status.dashio.net
  # Uncomment the `baseUrl` line if we don't have a custom domain and add our repo name there
  # baseUrl: /our-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/126912464?s=400&u=7b49febd424d1fe6eab8bc6f4b72b6ce85ecdebe&v=4
  favicon: https://dashio.net/favicon.ico
  name: Status
  introTitle: "Dashio Status Page"
  introMessage: Uptime monitor and status page built with GitHub. Leverages Issues for incident reporting, Actions for monitoring, and Pages for a transparent status display.
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
commitMessages:
  commitAuthorName: "DashioBot"
  commitAuthorEmail: "bots@dashio.net"
