owner: DashioDevs
repo: status

sites:
  - name: Hetzner Cloud Console
    url: https://console.hetzner.cloud
  - name: Dashio Website
    url: https://www.dashio.net
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add our custom domain name, or remove the `cname` line if we don't have a domain
  cname: status.dashio.net
  # Uncomment the `baseUrl` line if we don't have a custom domain and add our repo name there
  # baseUrl: /our-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/126912464?s=400&u=7b49febd424d1fe6eab8bc6f4b72b6ce85ecdebe&v=4
  name: Status
  introTitle: "With us, you secure maximum efficiency, security, and continuous growth."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/DashioDevs/status).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
